language: scala

scala:
   - 2.11.11
   - 2.12.8

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile test

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

before_install:
  - openssl aes-256-cbc -k "$ENC_PASSWORD" -in .secring.gpg.enc -out .secring.gpg -d
  - openssl aes-256-cbc -k "$ENC_PASSWORD" -in .pubring.gpg.enc -out .pubring.gpg -d

deploy:
  - provider: script
    script: sbt ++$TRAVIS_SCALA_VERSION "; publishSigned; sonatypeBundleRelease"
    skip_cleanup: true
    on:
      tags: true

jdk:
   - openjdk8

notifications:
  email:
    - r-and-d@slack.full360.com

env:
  # ENC_PASSWORD
  # SONATYPE_USERNAME
  # SONATYPE_PASSWORD
  # SONATYPE_KEY_NAME
  # SONATYPE_KEY_PASSPHRASE
  global:
    - secure: jlfT2uyJ0GVrRxojI2IsfIyoSlLFG9shHei9PlqdHcFXgAwa8jxs4sG6ph5b28aClw8pw75kic7rgEWRH6KXYFHc1/OGhcn7wDT+pwpBBGwZSyFLZgYdVZmMevi3xNBMQ8csghk/xH31ixUnprCMhyYKYp+hmsNE4/0sZrPqXb6zgwj+T67rXgfL4hZT08yPg/K3xZwF4fVlCBOJWvvmrcI6rLDDeymgTUp7Ywm1Mco/Qg1JWvp8kg2k4pbpjL0RMIbxrLwe9EO4pFDbC18jU5s1OYy4vFzoRwp3/m7zLTVt2MnzAxIeW9bemfyzx0Gi9G4oSUUCNYsgdqqkH2xXWTG5WMldg432TapJEoA02An7k3AeRRlySR+dtZIy0I3DVrKZ7MidKV5WaA5zfTsnaomZRsF7Xz83273We0tHfXAE7r14XkhZFVVOns76brehqeMbOqzvHQvw8nDHeV7JB9rCgXMSyxUwcHZL0NiSSl7vykhyPSCSs2AWO6r5aFlLdRRqty0NjxShXh+2384OXumxYY7VKjc9ma11bzzkdQW1RZT+MVb4WKEtjZ1cMzgq9BEhgrV6/wp1jFOOQMAmKi5/kLAuT6l4abwRbwaUxF5Be64iT90dk1VA6TibAUpgDi/7UE83/FpPpCwHyzS1+tMXRFB6evWKekUKuch7Z1I=
    - secure: SxGhEJmq+ICxNxjJdU3Lnhb6uQeprFAgBua04SAakKGNc237sk+toU2PcxoJrrNBP8rzZDiDse89rWsL06224UHCIJNF++9PtashmTcRzgPNYsE0mvzgiEV4/lLn9WX86zWN2X6RDqSdLiuk6oxPwi5ktwyuofqAYk5tpCPHec29IVDqP3oKk6pua6GVIKu8NwltU4TgoUvYyooZbqIQLIjmjzCP1DFbhcmbPQX+Z6g05kjTPTPnkQLLm6CtOqA//zW+H3QhlV/pGKF0Tp4XL/k3er/1XwvqvfVqXy4JrWL65T+qwOPkQMr2PV4sJqMlgzI4gaGwXm1lFvppNVAp6j6zOQJ208J0sGMPFvMH2gVfzZiZAlhF7ziIy8puJgI9Yr8DvVyObq+U6pcfHEhT1abWKgHB1RJmgY5pZLfW8lrjNPaXBZTy0THnk08998STRQmsKfRAguMdjTjRrwIhPuvmmRiPDGDgQbDxbvgTChq9TwoqDAOAOZrqLtH0npXNtGtafoDeEDSnva90B+VTNhAkmRrx85AodtKdnYcaZWxz3wHzGjD0LKl4kE2uBCrl6aOzPW9fHPHVzuLBToYPlHcI4ehmHpkLptDmo6X/ucwDuo4d4RbTn5CX+1c19YITqffamZfsmDcFXJCuUWxyoUKrU49UCIYMhIkaSVoRPt4=
    - secure: GrNjgY50KcxMMuQp8siwMMD8bmI63Y6wD02ZQLJ5KFeV4d6Kq1nEw8ZBy+tUbkoYl/uxMtKfVqM2vRGv0ipKkF2v6gdmDSy2PVJ+CzWkxUYIwm77sVOk9kA4A/y2XivvuPszF1GRhwvU8J72AM+1GQR4rIIGJYapXttjPPie/k3cuYvsZA5IezY+G4KO52fapPTckEzp4rBtBNanf0oZxvixJvCSfRWrEip0U3JhKjSSwJWi0aj1MVE7Z5vDFdodFHu1gDKKJYZEGM1pIjwH9aHybxRCjQlKLJoUN9+MY60DnA7jmbQONVA6NJSN+xHe3ldODfZyUdC4Gw/G3myvepkjCdxqFIZG6n+eGG5pHBU+euxYkFlvF58gsTYRcVMXme06JgxDEzorfSdtbb2MN+7ZKTWliQgwp3yOx1Yu7wmXlo+GqyhL4pUCJ9N9S66Ude3XqxpM7qglXq0lCNuQCHYarbsL2s9Sh27AlRlLe6O6NXkyOth04yD3q69VinG7i5heE6LBzs7WCO5InI4iGPEX8c4Ie+DzHdLOaZatZZDqvRrUCkn+7Mc0eg0HfWnpZBcFS5cRESwklmQPVlqcklsRs6cUscKQeX4klw5Oldxfot6qB9dJGbObFFpDZWDqOttXJWLKJf27LhVOPUsYRjCoQD9YR4VceGJC3JIHEVs=
    - secure: Rzbnc5l8nFrO8Z2FN6ObTMa2hkdf+bj8u2kButNyodFT8oPW5khiwe9jjS+wBJNVdhJdk4ycNwXCIXvh7ItcXAEYdw8MOETe8gGk1FiE7aHvC8lemn1+gB3ep7uAmOc62STXGoW5OVeXdlw8cdJG1FRwJFlJucLSIrqpa4DR8zV1QloUSUo3NvPTmO1exUC8l2XvVefDAyETWktm1U9adfOMA95qYRXAEodQo4rEcfZMM4GZhg5mpYoHz6w4SuNbu48MJEGCsY3VGC130eeJfHr7tlaq36obx4TzpxRBUgDKk+MaUtVHynHAMIeNYPG3k2pyHV4Pe2u/trSM/s6qRc+gez00JQxwfPucVIyLjRILROLXKve8eHX1G0Ez0TFZ/jpnoqv8aFoLVH4aGkJ6FQIbaAQnxF90tzJ+20qVG7yJbCLKfNvCVWJ+OGobFTIEMBzNUVMu24zCOvaQB8ly3OD6jiAAnruS92t8rPrf6wI71TZ3ucCJMXZtK/3RyVM+ng9O1nViW+k8bGz/QzVxq32n66oG6U9lnIx9hr9KdV75Be5TMU11a6Jde27aDxc7BHIkPO4zqJLKi1nmpYAqUT7uJhBRijnunrJmwxahWd9VDUN/mjoVJXh52hC/1qrWv7MIaLWm9clDR2bvlncp7PYTe9nLKfVo74z8qG3i+10=
    - secure: FbR5BSzQQblo4OPZtqSlPBz7t4hiXeFY2Pqq/j3RajAfU2C82L0wrg5+NRE8yqT9egpyPtE3klHZr2zWFmGXsEHv6I9x9xlVxsWczi92Tg27f6cW5TDw3/X3W4XcKE+TCGQEA0VfIQdYUVD+vmh61gyuDChHrTck+cvCNWbmYojLFDtR4kb1QDV2zh4v3LK6JZ5k9NIbmev+KTK9pMk8fl/ztpHOXI5AW3yQKHfS/0o1XB3gbzV2d8JdDzEN3Cw5ftbUSR1y3SUT7e63HXocKpghvikhdOrl0x4B4OFtYF/Y2Bg5N91RhaIDlPmZoxF2xAFf2uIhGNCctFsPXGJPFp0nhiKhjUPUJ240yraIEoVtYmegGjkUizrHDr76FTnM8tbjmWmYd3YiDooilKPvbe2rN/QGqYdSCthcWBR0Zlgi150JEaVpisTMy1rlsxhOUUJRl9Kc3TX3rBbZSBJUoIxkT/NehQg/Lmv3LyCkjyEsP57/am02IuAhwJ7niT6NM0zti4zE+L8jE7RDBY3wm3EZ7TaN9VWp8cQDPtkmubCVRJE2wguEauQg8qr2FhGOry50ho7y+tS7xCq3U4ac0xh0uP2ti2ILmfnDk6OVI2yOMvYKqmDLmPIYX0mPiUfxS74V8pzMyeBJ3nieXIqZKgwfNGuVMClt3OadwfSly1E=
